name = "deep-research"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
ACCESS_PASSWORD = "xhwwl3000"
OPENAI_COMPATIBLE_API_KEY="sk-6m1vvnComq02YyF279ECcqSpeVAT4ng07tonSl1EzqsfsVfs"
OPENAI_COMPATIBLE_API_BASE_URL="https://ai.999768.xyz"
